# Generated by Django 4.2.6 on 2023-11-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='apidata',
        ),
    ]
